
## Obtener asistentes
GET http://localhost:3000/api/asistentes HTTP/1.1
content-type: application/json

### Registrar asistente
POST http://localhost:3000/api/asistente HTTP/1.1
content-type: application/json

{
    "NOMBRE_Y_APELLIDOS": "Jeison Ferrer",
    "CEDULA": "1093795078",
    "CORREO": "jeison@example.com",
    "AREA_O_DEPENDENCIA": "Sistemas"
}

### Asignar RFID
PATCH http://localhost:3000/api/asignacionRfid/6Jc7W6ro8gM3wAKW968y HTTP/1.1
content-type: application/json

{
    "rfid": "A1B2C3D4E5"
}

### Buscar asistente por nombre
GET http://localhost:3000/api/asistentePorNombreOCedula/Jeison%20Ferrer HTTP/1.1



### Buscar asistente por cédula
GET http://localhost:3000/api/asistentePorNombreOCedula/1093795078 HTTP/1.1


### Registrar asistencia
PATCH http://localhost:3000/api/registrarAsistencia/9ziFqOhFPZnt9UltL4nG
Content-Type: application/json

{
  "mesa": "Mesa 2"
}


### Registrar asistencia localmente
POST http://localhost:3000/api/registrarAsistenciaLocal
Content-Type: application/json

{
  "cedula": "101020202",
  "mesa": "Mesa 6"
}


### Obtener asistencias locales
GET http://localhost:3000/api/asistenciasLocales HTTP/1.1

### Registrar asistencias locales en la base de datos
PATCH http://localhost:3000/api/registrarAsistenciasLocalesEnDb HTTP/1.1
Content-Type: application/json


### Registrar asistente
POST http://localhost:3000/api/asistente
Content-Type: application/json

{
  "NOMBRE_Y_APELLIDOS": "MARIA ISABEL VARGAS CARDENAS",
  "CEDULA": "1090505060",
  "CORREO": "contabilidad@imsalud.gov.co",
  "AREA_O_DEPENDENCIA": "CONTABILIDAD"
}
